apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq-cluster-ns
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: rabbitmq-cluster-ns
  name: rabbit-storage-class
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_ZRS
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: rabbit-storage-claim
#   namespace: rabbitmq-cluster-ns
#   annotations:
#     volume.beta.kubernetes.io/storage-class: rabbit-storage-class
# spec:
#   accessModes:
#   - ReadWriteMany
#   storageClassName: rabbit-storage-class
#   resources:
#     requests:
#       storage: 20Gi
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  namespace: rabbitmq-cluster-ns
  name: rabbitmq-cluster
spec:
  replicas: 1
  persistence:
    storageClassName: rabbit-storage-class
    storage: 10Gi